import Footer from '@/app/components/footer/Footer'
import Navbar from './components/navbar/Navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoidContextProvider from './recoilContextProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

      <html lang="en">
        <body className={inter.className}>
          <RecoidContextProvider>
            <Navbar/>
            <main className='m-auto min-w-[300px] max-w-7x1'>{children}</main>
          </RecoidContextProvider>
          <Footer/>
        </body>
      </html>
  )
}
